/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options passed to `Store.open`. */
export interface StoreOptions {
  /**
   * When `true`, the underlying `SQLite` database is opened in read-only
   * mode. Any attempt to write (insert, update, delete) will reject with
   * `code: "ReadOnly"`.
   *
   * Defaults to `false` (read-write) when omitted.
   */
  readOnly?: boolean
}
/** Options for `Store.search`. */
export interface SearchOptions {
  /**
   * Search mode. One of: `"auto"` | `"lexical"` | `"semantic"` | `"hybrid"`.
   * Default: `"auto"` (uses whichever sidecars are present).
   */
  mode?: string
  /** Maximum number of hits to return. Default: `10`. */
  limit?: number
  /** Per-ranker overfetch factor. Default: `3`. */
  fetchMultiplier?: number
  /** RRF damping constant. Default: `60`. */
  rrfK?: number
}
/** Options for `Store.retrieve`. */
export interface RetrieveOptions {
  /** Default: `"auto"`. One of: `"auto"` | `"lexical"` | `"semantic"` | `"hybrid"`. */
  mode?: string
  /** Default: `10`. */
  limit?: number
  /** Per-ranker overfetch factor. Default: `3`. */
  fetchMultiplier?: number
  /** RRF damping constant. Default: `60`. */
  rrfK?: number
  /** Default: `0.0`. Drop blocks whose score is below this threshold. */
  minScore?: number
}
/** Options passed to `Store.list`. */
export interface ListOptions {
  /**
   * Restrict results to items that have ALL of these tags (AND-semantics).
   *
   * An item is included only if every tag in this array appears in the
   * item's `tags` field. An empty array (or omitting `tags` entirely)
   * returns all items without tag filtering.
   */
  tags?: Array<string>
  /**
   * Cap the number of items returned at this value.
   *
   * The limit is applied after tag filtering, on the oldest-first ordered
   * result set. Omit or pass `undefined` to return all matching items.
   */
  limit?: number
}
/**
 * An item retrieved from the store.
 *
 * All string values are UTF-8. `createdAt` is a JS `Date` constructed from
 * the millisecond-precision wall-clock time the store assigned at ingest.
 *
 * **Precision caveat:** the core layer stores timestamps at nanosecond
 * precision, but the JS `Date` type only supports millisecond precision.
 * Any sub-millisecond component of `createdAt` is silently truncated when
 * crossing the native boundary.
 */
export interface Item {
  /**
   * Unique item identifier: a 26-character Crockford base32 ULID string.
   *
   * ULIDs are lexicographically sortable by creation time. The string is
   * always uppercase and exactly 26 characters long.
   */
  id: string
  /** The item's main text payload, encoded as UTF-8. */
  content: string
  /**
   * Wall-clock time the store assigned at ingest, as a JS `Date`.
   *
   * **Precision caveat:** the underlying store records nanosecond precision;
   * sub-millisecond digits are lost when the value crosses the native
   * boundary and is represented as a JS `Date` (millisecond precision only).
   */
  createdAt: Date
  /**
   * ULID of the item this item supersedes, or `undefined` if this item does
   * not replace a prior one.
   *
   * Following the chain of `supersedes` links from newest to oldest
   * reconstructs the full revision history of a logical memory entry.
   */
  supersedes?: string
  /**
   * Tags attached to the item.
   *
   * The array is always sorted lexicographically and deduplicated; no tag
   * appears more than once.
   */
  tags: Array<string>
  /**
   * Optional free-form provenance label identifying the source of the item
   * (e.g. `"user"`, `"llm"`, `"import"`). `undefined` if not set.
   */
  source?: string
  /**
   * Arbitrary user-defined JSON object attached to the item.
   *
   * The value is always an object (never `null`, an array, or a scalar).
   * Defaults to an empty object `{}` when no metadata was provided at
   * ingest time.
   */
  metadata: any
}
/** One result from `Store.search`. The full `Item` is always populated. */
export interface SearchHit {
  /** The matched item. */
  item: Item
  /** Final score after fusion (RRF) or single-ranker (BM25 / cosine). */
  score: number
  /** Which ranker produced the score: "rrf" | "bm25" | "cosine". */
  kind: string
  /**
   * 1-based rank in the lexical (Tantivy) ranker, present only when
   * the lexical ranker ran (hybrid + lexical modes).
   */
  lexicalRank?: number
  /**
   * 1-based rank in the semantic (`USearch`) ranker, present only when
   * the semantic ranker ran (hybrid + semantic modes).
   */
  semanticRank?: number
}
/** Results returned by `Store.search`. */
export interface SearchResults {
  query: string
  hits: Array<SearchHit>
}
/**
 * One block in a `RetrievedContext`. Flat shape matching
 * `singularmem_retrieve::MemoryBlock` (no nested Item).
 */
export interface MemoryBlock {
  /** 26-character Crockford base32 ULID. */
  id: string
  /** Full UTF-8 content from the store (not a snippet). */
  content: string
  /** Score whose meaning depends on `kind`. */
  score: number
  /** "rrf" | "bm25" | "cosine". */
  kind: string
  /** Free-form provenance label from the matched item. */
  source?: string
  /** Tags from the matched item. Sorted, deduplicated. */
  tags: Array<string>
  /**
   * Wall-clock time the matched item was ingested, as ms since epoch.
   * Lossy: ms precision vs core's ns precision (same as Item.createdAt).
   */
  createdAt: Date
}
/** Structured retrieval context returned by `Store.retrieve`. */
export interface RetrievedContext {
  query: string
  blocks: Array<MemoryBlock>
}
/** Returns the crate version. Used as a smoke-test export. */
export declare function version(): string
/**
 * A handle to a Singularmem store on disk.
 *
 * Obtain an instance via the async static factory `Store.open`. All methods
 * are async and resolve on the libuv thread pool so the JS event loop is
 * never blocked.
 *
 * Errors are always thrown as `Error` objects with a structured `.code`
 * string property. See the README for the full list of possible codes.
 */
export declare class Store {
  /**
   * Open (or create) a Singularmem store at the given filesystem path.
   *
   * The `SQLite` database file is created automatically if it does not exist.
   * Schema migrations run at open time; if the on-disk format is newer than
   * this binding supports the promise rejects with `UnsupportedFormatVersion`.
   *
   * @param path Absolute or relative path to the `SQLite` database file.
   *   Must be a non-empty string; rejects with `InvalidStorePath` otherwise.
   * @param options Optional open options (see `StoreOptions`).
   * @returns A ready-to-use `Store` instance.
   * @throws `{ code: "InvalidStorePath" }` — path is empty or otherwise invalid.
   * @throws `{ code: "UnsupportedFormatVersion" }` — store file is newer than this binding supports.
   * @throws `{ code: "Sqlite" }` — underlying `SQLite` error (e.g. permissions, corrupt file).
   * @throws `{ code: "Io" }` — filesystem or I/O error.
   */
  static open(path: string, options?: StoreOptions | undefined | null): Promise<Store>
  /**
   * Retrieve a single item by its ULID string.
   *
   * @param id A 26-character Crockford base32 ULID string identifying the item.
   * @returns The matching `Item`.
   * @throws `{ code: "NotFound" }` — no item with that ID exists in the store.
   * @throws `{ code: "InvalidId" }` — `id` is not a valid 26-character ULID string.
   * @throws `{ code: "Sqlite" }` — underlying `SQLite` error.
   */
  get(id: string): Promise<Item>
  /**
   * List items in the store, ordered oldest to newest by ingest time.
   *
   * **Tag filtering (AND-semantics):** when `options.tags` is provided,
   * only items that carry *every* listed tag are returned. An empty `tags`
   * array is equivalent to omitting the field (no filtering).
   *
   * **Limit:** when `options.limit` is provided, the result array is
   * truncated to at most that many items after tag filtering is applied.
   *
   * @param options Optional filtering and pagination options (see `ListOptions`).
   * @returns Array of matching `Item` objects, oldest first.
   * @throws `{ code: "Sqlite" }` — underlying `SQLite` error.
   */
  list(options?: ListOptions | undefined | null): Promise<Array<Item>>
  /**
   * Return the full revision history for a logical memory entry.
   *
   * Pass the ULID of *any* item in a supersession chain (not necessarily
   * the oldest or newest). The method walks the chain and returns every
   * revision ordered oldest to newest (i.e. the first element was ingested
   * first and each subsequent element supersedes the previous one).
   *
   * @param id A 26-character Crockford base32 ULID of any item in the chain.
   * @returns Array of `Item` objects in chronological order (oldest first).
   * @throws `{ code: "NotFound" }` — no item with that ID exists in the store.
   * @throws `{ code: "InvalidId" }` — `id` is not a valid 26-character ULID string.
   * @throws `{ code: "AmbiguousLatest" }` — the revision chain forks (data integrity error).
   * @throws `{ code: "Sqlite" }` — underlying `SQLite` error.
   */
  revisions(id: string): Promise<Array<Item>>
  /**
   * Run a hybrid search over the store's indexes.
   *
   * Probes for Tantivy (`.tantivy`) and vector (`.vectors`) sidecars next to
   * the store file on each call (no caching). The `mode` option controls
   * which rankers run; defaults to `"auto"` (use whatever's available).
   *
   * @param query The natural-language search query.
   * @param options Optional `{ mode?, limit?, fetchMultiplier?, rrfK? }`.
   * @returns `SearchResults` with the query echoed and per-hit `Item` content.
   * @throws `Error` with `.code === "NoIndexes"` if mode is `"auto"` and no sidecars exist.
   * @throws `Error` with `.code === "HybridMissingIndex"` if mode is `"hybrid"` and one sidecar is missing.
   * @throws `Error` with `.code === "IndexMissing"` if an explicit mode requires a missing sidecar.
   * @throws `Error` with `.code === "Validation"` if the mode string is unrecognised.
   */
  search(query: string, options?: SearchOptions | undefined | null): Promise<SearchResults>
  /**
   * Retrieve a structured context for the given query.
   *
   * Runs hybrid search, fetches the full Item for each hit, drops blocks
   * below `minScore`, and returns the resulting `RetrievedContext`. Pass
   * the result to one of `adapters.{plain,claude,openai,gemini}.format()`
   * for prompt-ready output.
   *
   * @param query The natural-language query. Must be non-empty.
   * @param options Optional `{ mode?, limit?, fetchMultiplier?, rrfK?, minScore? }`.
   * @returns `RetrievedContext` with `query` echoed and `blocks` populated.
   * @throws `Error` with `.code === "EmptyQuery"` if the query is empty or
   *   whitespace-only.
   * @throws Same `.code` set as `Store.search` for index-related issues
   *   (`NoIndexes`, `HybridMissingIndex`, `IndexMissing`, etc.).
   */
  retrieve(query: string, options?: RetrieveOptions | undefined | null): Promise<RetrievedContext>
  /**
   * Return the on-disk format version recorded in this store file.
   *
   * The version is a semver string (e.g. `"1.0.0"`) that identifies the
   * schema and serialisation format used by the store. This value is written
   * once when the store is first created and is validated at open time; if
   * the version is newer than what this binding understands, `Store.open`
   * rejects with `UnsupportedFormatVersion`.
   *
   * @returns A semver version string such as `"1.0.0"`.
   * @throws `{ code: "Sqlite" }` — underlying `SQLite` error.
   */
  formatVersion(): Promise<string>
  /**
   * Export the entire store as a JSONL (newline-delimited JSON) string.
   *
   * The output format is one JSON object per line:
   * - **Line 1** — a metadata header object, e.g.
   *   `{"type":"meta","formatVersion":"1.0.0"}`.
   * - **Remaining lines** — one `Item`-shaped JSON object per stored item,
   *   in oldest-first order.
   *
   * The returned string is UTF-8 encoded. It can be written directly to a
   * `.jsonl` file for backup or migration purposes.
   *
   * @returns The full JSONL payload as a UTF-8 string.
   * @throws `{ code: "Sqlite" }` — underlying `SQLite` error.
   * @throws `{ code: "Json" }` — JSON serialisation error (should not occur in normal use).
   * @throws `{ code: "Io" }` — I/O error writing to the internal buffer.
   */
  export(): Promise<string>
}
