/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for `Store.open`. */
export interface StoreOptions {
  /**
   * If true, opens `SQLite` in read-only mode. Writes will error with
   * `code: "ReadOnly"`.
   */
  readOnly?: boolean
}
/** Options for `Store.list`. */
export interface ListOptions {
  /** Only return items tagged with ALL of these tags (AND-semantics). */
  tags?: Array<string>
  /** Maximum number of items to return. Applied after tag filtering. */
  limit?: number
}
/**
 * An item retrieved from the store.
 *
 * `createdAt` is a JS `Date` constructed from the wall-clock time the store
 * assigned at ingest. The core stores nanosecond precision; sub-millisecond
 * precision is lost when crossing the boundary.
 */
export interface Item {
  /** 26-character Crockford base32 ULID string. */
  id: string
  /** UTF-8 text content. */
  content: string
  /**
   * Wall-clock time the store assigned at ingest.
   * Lossy: ms precision vs core's ns precision.
   */
  createdAt: Date
  /** ID of the item this supersedes, if any. */
  supersedes?: string
  /** Tags attached to the item. Sorted, deduplicated. */
  tags: Array<string>
  /** Free-form provenance label. */
  source?: string
  /** Arbitrary user-defined JSON object. */
  metadata: any
}
/** Returns the crate version. Used as a smoke-test export. */
export declare function version(): string
/** A handle to a Singularmem store on disk. */
export declare class Store {
  /**
   * Open a store at the given filesystem path.
   *
   * @param path Absolute or relative path to a `SQLite` file (will be
   *   created if it does not exist).
   * @param options Optional `{ readOnly?: boolean }`.
   * @returns A `Store` instance.
   * @throws `Error` with `.code` from the standard set
   *   (`InvalidStorePath`, `Io`, `Sqlite`, `UnsupportedFormatVersion`, …).
   */
  static open(path: string, options?: StoreOptions | undefined | null): Promise<Store>
  /**
   * Look up a single item by its ULID.
   *
   * @param id A 26-character Crockford base32 ULID string.
   * @returns The matching item.
   * @throws `Error` with `.code === "NotFound"` if the ID does not exist.
   * @throws `Error` with `.code === "InvalidId"` if the string is not a valid ULID.
   */
  get(id: string): Promise<Item>
  /**
   * List items in the store, ordered oldest → newest by ingest time.
   *
   * @param options Optional `{ tags?: string[]; limit?: number }`.
   *   When `tags` is given, items must contain ALL listed tags.
   *   When `limit` is given, the returned array is capped at that length.
   * @returns Array of items.
   */
  list(options?: ListOptions | undefined | null): Promise<Array<Item>>
}
