/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options passed to `Store.open`. */
export interface StoreOptions {
  /**
   * When `true`, the underlying `SQLite` database is opened in read-only
   * mode. Any attempt to write (insert, update, delete) will reject with
   * `code: "ReadOnly"`.
   *
   * Defaults to `false` (read-write) when omitted.
   */
  readOnly?: boolean
}
/** Options for `Store.search`. */
export interface SearchOptions {
  /**
   * Search mode. One of: `"auto"` | `"lexical"` | `"semantic"` | `"hybrid"`.
   *
   * - `"auto"` (default) — probe which sidecars exist; run hybrid if both are
   *   present, fall back to whichever single ranker is available.
   * - `"lexical"` — Tantivy BM25 only; rejects with `IndexMissing` if absent.
   * - `"semantic"` — `USearch` cosine only; rejects with `IndexMissing` if absent.
   * - `"hybrid"` — both rankers, RRF-fused; rejects with `HybridMissingIndex`
   *   if either sidecar is missing.
   */
  mode?: string
  /** Maximum number of hits to return. Default: `10`. */
  limit?: number
  /**
   * Per-ranker overfetch factor used to build candidates before fusion or
   * trimming. Effective candidates = `limit × fetchMultiplier`. Default: `3`.
   */
  fetchMultiplier?: number
  /**
   * Reciprocal Rank Fusion damping constant. Higher values reduce the impact
   * of high-ranked documents. Default: `60`.
   */
  rrfK?: number
}
/** Options for `Store.retrieve`. */
export interface RetrieveOptions {
  /**
   * Search mode. One of: `"auto"` | `"lexical"` | `"semantic"` | `"hybrid"`.
   * Default: `"auto"`. Semantics are identical to `SearchOptions.mode`.
   */
  mode?: string
  /** Maximum number of blocks to return (after score filtering). Default: `10`. */
  limit?: number
  /**
   * Per-ranker overfetch factor. Default: `3`. Same meaning as in
   * `SearchOptions.fetchMultiplier`.
   */
  fetchMultiplier?: number
  /**
   * Reciprocal Rank Fusion damping constant. Default: `60`. Same meaning as
   * in `SearchOptions.rrfK`.
   */
  rrfK?: number
  /**
   * Drop blocks whose score is strictly below this threshold. Default: `0.0`
   * (keep all blocks). Useful for filtering out low-relevance results before
   * passing to an adapter.
   */
  minScore?: number
}
/** Options passed to `Store.list`. */
export interface ListOptions {
  /**
   * Restrict results to items that have ALL of these tags (AND-semantics).
   *
   * An item is included only if every tag in this array appears in the
   * item's `tags` field. An empty array (or omitting `tags` entirely)
   * returns all items without tag filtering.
   */
  tags?: Array<string>
  /**
   * Cap the number of items returned at this value.
   *
   * The limit is applied after tag filtering, on the oldest-first ordered
   * result set. Omit or pass `undefined` to return all matching items.
   */
  limit?: number
}
/**
 * An item retrieved from the store.
 *
 * All string values are UTF-8. `createdAt` is a JS `Date` constructed from
 * the millisecond-precision wall-clock time the store assigned at ingest.
 *
 * **Precision caveat:** the core layer stores timestamps at nanosecond
 * precision, but the JS `Date` type only supports millisecond precision.
 * Any sub-millisecond component of `createdAt` is silently truncated when
 * crossing the native boundary.
 */
export interface Item {
  /**
   * Unique item identifier: a 26-character Crockford base32 ULID string.
   *
   * ULIDs are lexicographically sortable by creation time. The string is
   * always uppercase and exactly 26 characters long.
   */
  id: string
  /** The item's main text payload, encoded as UTF-8. */
  content: string
  /**
   * Wall-clock time the store assigned at ingest, as a JS `Date`.
   *
   * **Precision caveat:** the underlying store records nanosecond precision;
   * sub-millisecond digits are lost when the value crosses the native
   * boundary and is represented as a JS `Date` (millisecond precision only).
   */
  createdAt: Date
  /**
   * ULID of the item this item supersedes, or `undefined` if this item does
   * not replace a prior one.
   *
   * Following the chain of `supersedes` links from newest to oldest
   * reconstructs the full revision history of a logical memory entry.
   */
  supersedes?: string
  /**
   * Tags attached to the item.
   *
   * The array is always sorted lexicographically and deduplicated; no tag
   * appears more than once.
   */
  tags: Array<string>
  /**
   * Optional free-form provenance label identifying the source of the item
   * (e.g. `"user"`, `"llm"`, `"import"`). `undefined` if not set.
   */
  source?: string
  /**
   * Arbitrary user-defined JSON object attached to the item.
   *
   * The value is always an object (never `null`, an array, or a scalar).
   * Defaults to an empty object `{}` when no metadata was provided at
   * ingest time.
   */
  metadata: any
}
/** One result from `Store.search`. The full `Item` is always populated. */
export interface SearchHit {
  /** The matched item. */
  item: Item
  /** Final score after fusion (RRF) or single-ranker (BM25 / cosine). */
  score: number
  /** Which ranker produced the score: "rrf" | "bm25" | "cosine". */
  kind: string
  /**
   * 1-based rank in the lexical (Tantivy) ranker, present only when
   * the lexical ranker ran (hybrid + lexical modes).
   */
  lexicalRank?: number
  /**
   * 1-based rank in the semantic (`USearch`) ranker, present only when
   * the semantic ranker ran (hybrid + semantic modes).
   */
  semanticRank?: number
}
/** Results returned by `Store.search`. */
export interface SearchResults {
  /** The query string echoed back from the search call. */
  query: string
  /**
   * Ranked list of search hits, sorted by descending score. May be empty
   * if no items matched the query.
   */
  hits: Array<SearchHit>
}
/**
 * One block in a `RetrievedContext`. Flat shape matching
 * `singularmem_retrieve::MemoryBlock` (no nested Item).
 */
export interface MemoryBlock {
  /** 26-character Crockford base32 ULID. */
  id: string
  /** Full UTF-8 content from the store (not a snippet). */
  content: string
  /** Score whose meaning depends on `kind`. */
  score: number
  /** "rrf" | "bm25" | "cosine". */
  kind: string
  /** Free-form provenance label from the matched item. */
  source?: string
  /** Tags from the matched item. Sorted, deduplicated. */
  tags: Array<string>
  /**
   * Wall-clock time the matched item was ingested, as a JS `Date`.
   *
   * **Precision caveat:** the core layer stores timestamps at nanosecond
   * precision. Any sub-millisecond component is silently truncated when
   * crossing the native boundary (same behaviour as `Item.createdAt`).
   */
  createdAt: Date
}
/** Structured retrieval context returned by `Store.retrieve`. */
export interface RetrievedContext {
  /** The query string echoed back from the retrieve call. */
  query: string
  /**
   * Ordered list of memory blocks, sorted by descending score and filtered
   * by `minScore`. Pass this directly to an adapter's `format()` method.
   */
  blocks: Array<MemoryBlock>
}
/**
 * Input to `Store.ingest`. Only `content` is required; other fields apply
 * sensible defaults when omitted.
 */
export interface NewItem {
  /** Required: UTF-8 text content. Must be non-empty, ≤ 1 MiB. */
  content: string
  /** Optional: ULID of the item this supersedes (revision chain). */
  supersedes?: string
  /** Optional: tags to attach. Default: `[]`. Duplicates are silently deduped. */
  tags?: Array<string>
  /** Optional: free-form provenance label, ≤ 256 bytes. */
  source?: string
  /**
   * Optional: arbitrary JSON object (must be an object, not an array or
   * scalar). Default: `{}` when omitted.
   */
  metadata?: any
}
/** Returns the crate version. Used as a smoke-test export. */
export declare function version(): string
/** Plain Markdown adapter. */
export declare class PlainAdapter {
  constructor()
  /** The adapter's stable name; matches `adapter.name` on the JS side. */
  get name(): string
  /** Format the given context as Markdown blocks. */
  format(ctx: RetrievedContext): string
}
/**
 * Anthropic Claude `<documents>` XML adapter.
 *
 * Formats a `RetrievedContext` as Anthropic's canonical document-list XML,
 * using `<documents><document index="N"><source>…</source><document_content>…
 * </document_content></document>…</documents>` structure. Suitable for use
 * in Claude system prompts or user turns.
 */
export declare class ClaudeAdapter {
  constructor()
  /** The adapter's stable name — always `"claude"`. */
  get name(): string
  /** Format the given context as Anthropic Claude `<documents>` XML. */
  format(ctx: RetrievedContext): string
}
/**
 * `OpenAI` bracketed-citation adapter.
 *
 * Formats a `RetrievedContext` as numbered `[1]`, `[2]`, … citation blocks
 * preceded by an instruction line that asks the model to cite sources by
 * their bracketed number. Suitable for `OpenAI` API `system` or `user` turns.
 */
export declare class OpenAiAdapter {
  constructor()
  /** The adapter's stable name — always `"openai"`. */
  get name(): string
  /** Format the given context as bracketed `[N]` citation blocks. */
  format(ctx: RetrievedContext): string
}
/**
 * Google Gemini em-dash "Source N" adapter.
 *
 * Formats a `RetrievedContext` using em-dash `— Source N —` section headers
 * followed by a grounding directive, suitable for Gemini API `system` or
 * `user` message parts.
 */
export declare class GeminiAdapter {
  constructor()
  /** The adapter's stable name — always `"gemini"`. */
  get name(): string
  /** Format the given context as em-dash `Source N` blocks. */
  format(ctx: RetrievedContext): string
}
/**
 * A handle to a Singularmem store on disk.
 *
 * Obtain an instance via the async static factory `Store.open`. All methods
 * are async and resolve on the libuv thread pool so the JS event loop is
 * never blocked.
 *
 * Errors are always thrown as `Error` objects with a structured `.code`
 * string property. See the README for the full list of possible codes.
 */
export declare class Store {
  /**
   * Open (or create) a Singularmem store at the given filesystem path.
   *
   * The `SQLite` database file is created automatically if it does not exist.
   * Schema migrations run at open time; if the on-disk format is newer than
   * this binding supports the promise rejects with `UnsupportedFormatVersion`.
   *
   * @param path Absolute or relative path to the `SQLite` database file.
   *   Must be a non-empty string; rejects with `InvalidStorePath` otherwise.
   * @param options Optional open options (see `StoreOptions`).
   * @returns A ready-to-use `Store` instance.
   * @throws `{ code: "InvalidStorePath" }` — path is empty or otherwise invalid.
   * @throws `{ code: "UnsupportedFormatVersion" }` — store file is newer than this binding supports.
   * @throws `{ code: "Sqlite" }` — underlying `SQLite` error (e.g. permissions, corrupt file).
   * @throws `{ code: "Io" }` — filesystem or I/O error.
   */
  static open(path: string, options?: StoreOptions | undefined | null): Promise<Store>
  /**
   * Retrieve a single item by its ULID string.
   *
   * @param id A 26-character Crockford base32 ULID string identifying the item.
   * @returns The matching `Item`.
   * @throws `{ code: "NotFound" }` — no item with that ID exists in the store.
   * @throws `{ code: "InvalidId" }` — `id` is not a valid 26-character ULID string.
   * @throws `{ code: "Sqlite" }` — underlying `SQLite` error.
   */
  get(id: string): Promise<Item>
  /**
   * List items in the store, ordered oldest to newest by ingest time.
   *
   * **Tag filtering (AND-semantics):** when `options.tags` is provided,
   * only items that carry *every* listed tag are returned. An empty `tags`
   * array is equivalent to omitting the field (no filtering).
   *
   * **Limit:** when `options.limit` is provided, the result array is
   * truncated to at most that many items after tag filtering is applied.
   *
   * @param options Optional filtering and pagination options (see `ListOptions`).
   * @returns Array of matching `Item` objects, oldest first.
   * @throws `{ code: "Sqlite" }` — underlying `SQLite` error.
   */
  list(options?: ListOptions | undefined | null): Promise<Array<Item>>
  /**
   * Return the full revision history for a logical memory entry.
   *
   * Pass the ULID of *any* item in a supersession chain (not necessarily
   * the oldest or newest). The method walks the chain and returns every
   * revision ordered oldest to newest (i.e. the first element was ingested
   * first and each subsequent element supersedes the previous one).
   *
   * @param id A 26-character Crockford base32 ULID of any item in the chain.
   * @returns Array of `Item` objects in chronological order (oldest first).
   * @throws `{ code: "NotFound" }` — no item with that ID exists in the store.
   * @throws `{ code: "InvalidId" }` — `id` is not a valid 26-character ULID string.
   * @throws `{ code: "AmbiguousLatest" }` — the revision chain forks (data integrity error).
   * @throws `{ code: "Sqlite" }` — underlying `SQLite` error.
   */
  revisions(id: string): Promise<Array<Item>>
  /**
   * Run a hybrid search over the store's indexes.
   *
   * Probes for Tantivy (`.tantivy`) and vector (`.vectors`) sidecars next to
   * the store file on each call (no caching). The `mode` option controls
   * which rankers run; defaults to `"auto"` (use whatever's available).
   *
   * Build indexes first via the CLI:
   * `singularmem reindex --with-embeddings --store ./memory.db`
   *
   * @param query The natural-language search query string.
   * @param options Optional `{ mode?, limit?, fetchMultiplier?, rrfK? }`.
   * @returns `SearchResults` with the query echoed and per-hit `Item` content.
   * @throws `{ code: "NoIndexes" }` — `mode: "auto"` but no sidecar directories exist.
   * @throws `{ code: "HybridMissingIndex" }` — `mode: "hybrid"` and one of the two sidecars is absent.
   * @throws `{ code: "IndexMissing" }` — explicit `mode: "lexical"` or `"semantic"` requires a sidecar that is absent.
   * @throws `{ code: "IndexCorrupted" }` — a sidecar directory exists but cannot be opened.
   * @throws `{ code: "Validation" }` — the `mode` string is not one of the four recognised values.
   * @throws `{ code: "QueryParse" }` — Tantivy could not parse the query string.
   * @throws `{ code: "Tantivy" }` — Tantivy runtime error during search.
   * @throws `{ code: "Usearch" }` — `USearch` runtime error during search.
   * @throws `{ code: "Embedding" }` — embedder runtime error while encoding the query.
   * @throws `{ code: "ModelDownload" }` — fastembed model files could not be downloaded.
   * @throws `{ code: "InvalidModelFiles" }` — embedder model files on disk are malformed.
   * @throws `{ code: "DimMismatch" }` — the vector index was built with a different embedding dimension.
   * @throws `{ code: "ModelMismatch" }` — the vector index was built with a different embedder model.
   */
  search(query: string, options?: SearchOptions | undefined | null): Promise<SearchResults>
  /**
   * Retrieve a structured context for the given query.
   *
   * Runs hybrid search, fetches the full Item for each hit, drops blocks
   * below `minScore`, and returns the resulting `RetrievedContext`. Pass
   * the result to one of `adapters.{plain,claude,openai,gemini}.format()`
   * for prompt-ready output.
   *
   * @param query The natural-language query string. Must be non-empty and
   *   not purely whitespace; rejects immediately with `EmptyQuery` otherwise.
   * @param options Optional `{ mode?, limit?, fetchMultiplier?, rrfK?, minScore? }`.
   * @returns `RetrievedContext` with `query` echoed and `blocks` populated.
   * @throws `{ code: "EmptyQuery" }` — the query is empty or whitespace-only.
   * @throws `{ code: "NoIndexes" }` — `mode: "auto"` but no sidecar directories exist.
   * @throws `{ code: "HybridMissingIndex" }` — `mode: "hybrid"` and one sidecar is absent.
   * @throws `{ code: "IndexMissing" }` — explicit mode requires a sidecar that is absent.
   * @throws `{ code: "IndexCorrupted" }` — a sidecar directory exists but cannot be opened.
   * @throws `{ code: "Validation" }` — the `mode` string is unrecognised.
   * @throws `{ code: "QueryParse" }` — Tantivy could not parse the query string.
   * @throws `{ code: "Tantivy" }` — Tantivy runtime error during search.
   * @throws `{ code: "Usearch" }` — `USearch` runtime error during search.
   * @throws `{ code: "Embedding" }` — embedder runtime error while encoding the query.
   * @throws `{ code: "ModelDownload" }` — fastembed model files could not be downloaded.
   * @throws `{ code: "InvalidModelFiles" }` — embedder model files on disk are malformed.
   * @throws `{ code: "DimMismatch" }` — vector index built with a different embedding dimension.
   * @throws `{ code: "ModelMismatch" }` — vector index built with a different embedder model.
   */
  retrieve(query: string, options?: RetrieveOptions | undefined | null): Promise<RetrievedContext>
  /**
   * Persist a new item to the store.
   *
   * If Tantivy + `USearch` sidecars exist at the store path, the new item
   * is written to those indexes too (via per-call hook attachment). Hook
   * write failures during ingest are logged via `tracing::warn!` but do
   * NOT roll back the `SQLite` insert — the returned Item is durable
   * regardless of hook outcomes (Principle VII).
   *
   * @param item The item to persist. Only `content` is required; other
   *   fields apply sensible defaults when omitted.
   * @returns The newly-persisted Item with assigned `id` and `createdAt`.
   * @throws Error with `.code === "Validation"` if any field fails validation.
   * @throws Error with `.code === "InvalidId"` if `supersedes` is malformed.
   * @throws Error with `.code === "SupersedesNotFound"` if `supersedes`
   *   references a non-existent ID.
   * @throws Error with `.code === "ReadOnly"` if the store was opened with
   *   `{ readOnly: true }`.
   * @throws Error with `.code === "Sqlite"` on database errors.
   */
  ingest(item: NewItem): Promise<Item>
  /**
   * Return the on-disk format version recorded in this store file.
   *
   * The version is a semver string (e.g. `"1.0.0"`) that identifies the
   * schema and serialisation format used by the store. This value is written
   * once when the store is first created and is validated at open time; if
   * the version is newer than what this binding understands, `Store.open`
   * rejects with `UnsupportedFormatVersion`.
   *
   * @returns A semver version string such as `"1.0.0"`.
   * @throws `{ code: "Sqlite" }` — underlying `SQLite` error.
   */
  formatVersion(): Promise<string>
  /**
   * Export the entire store as a JSONL (newline-delimited JSON) string.
   *
   * The output format is one JSON object per line:
   * - **Line 1** — a metadata header object, e.g.
   *   `{"type":"meta","formatVersion":"1.0.0"}`.
   * - **Remaining lines** — one `Item`-shaped JSON object per stored item,
   *   in oldest-first order.
   *
   * The returned string is UTF-8 encoded. It can be written directly to a
   * `.jsonl` file for backup or migration purposes.
   *
   * @returns The full JSONL payload as a UTF-8 string.
   * @throws `{ code: "Sqlite" }` — underlying `SQLite` error.
   * @throws `{ code: "Json" }` — JSON serialisation error (should not occur in normal use).
   * @throws `{ code: "Io" }` — I/O error writing to the internal buffer.
   */
  export(): Promise<string>
}

/**
 * The four pre-built prompt adapters, keyed by provider name.
 *
 * Each adapter exposes:
 * - `name` — stable lowercase identifier (e.g. `"claude"`)
 * - `format(ctx)` — synchronous; converts a `RetrievedContext` into a
 *   provider-specific prompt string.
 *
 * Supported adapters:
 * - `adapters.plain`  — Markdown `## memory N` headings
 * - `adapters.claude` — Anthropic `<documents><document index="N">` XML
 * - `adapters.openai` — Bracketed `[N]` citations with a leading instruction
 * - `adapters.gemini` — Em-dash `Source N` headers with grounding directive
 */
export declare const adapters: {
  readonly plain: PlainAdapter
  readonly claude: ClaudeAdapter
  readonly openai: OpenAiAdapter
  readonly gemini: GeminiAdapter
}
